[package]
name = "aghpb-cli"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aghpb = "1.4.1"
owo-colors = "3.5.0"
bytes = "1.5.0"
tokio = { version = "1.34.0", features = ["rt", "macros"]}